spring.application.name=Online_Shop

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


spring.datasource.url=jdbc:mariadb://localhost:3306/myDB
#set your db username here before running
spring.datasource.username=dbuser
#set your pass here before running

spring.datasource.password=${PASSWORD_FOR_DATABASE}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




spring.security.user.name=
spring.security.user.password=
spring.security.user.roles=

#you enable this frist to turn on the feature
app.mail.enabled=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
 # your email and pass goes down here
spring.mail.username=${MAIL_USERNAME}
  
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true